-- Script para crear cliente Oxxo y sus sucursales
-- Fecha: 2025-10-31

-- 1. Crear el cliente Oxxo (si no existe)
DO $$
DECLARE
    v_client_id UUID;
BEGIN
    -- Verificar si el cliente ya existe
    SELECT id INTO v_client_id FROM clients WHERE name = 'Oxxo';

    IF v_client_id IS NULL THEN
        -- Crear el cliente Oxxo
        INSERT INTO clients (name, lead_status, billing_type, created_at)
        VALUES ('Oxxo', 'client', 'facturable', NOW())
        RETURNING id INTO v_client_id;

        RAISE NOTICE 'Cliente Oxxo creado con ID: %', v_client_id;
    ELSE
        RAISE NOTICE 'Cliente Oxxo ya existe con ID: %', v_client_id;
    END IF;

    -- 2. Crear las sucursales
    -- Primero crear la sucursal principal
    INSERT INTO branches (client_id, name, is_main, created_at, updated_at)
    VALUES (v_client_id, 'BOG 38617 RIONEGRO', true, NOW(), NOW())
    ON CONFLICT DO NOTHING;

    -- Insertar las demás sucursales
    INSERT INTO branches (client_id, name, is_main, created_at, updated_at)
    VALUES
        (v_client_id, 'BOG 27587 CALLE 100', false, NOW(), NOW()),
        (v_client_id, 'BOG 38829 MIRADOR DE PONTEVEDR', false, NOW(), NOW()),
        (v_client_id, 'BOG 38923 MERCADO LAS FERIAS B', false, NOW(), NOW()),
        (v_client_id, 'BOG 38867 LOS ANDES', false, NOW(), NOW()),
        (v_client_id, 'BOG 38933 LAS FERIAS', false, NOW(), NOW()),
        (v_client_id, 'BOG 39333 AVENIDA CONSTITUCION', false, NOW(), NOW()),
        (v_client_id, 'BOG 36657 SANTA MARIANA', false, NOW(), NOW()),
        (v_client_id, 'BOG 39341 SAN BASILIO', false, NOW(), NOW()),
        (v_client_id, 'BOG 15052 PRIMAVERA', false, NOW(), NOW()),
        (v_client_id, 'BOG 39395 PLAZUEA DEL VIRREY', false, NOW(), NOW()),
        (v_client_id, 'BOG 39343 PARQUE CENTRAL', false, NOW(), NOW()),
        (v_client_id, 'BOG 39165 GARCES NAVAS', false, NOW(), NOW()),
        (v_client_id, 'BOG 39349 BELMONTE', false, NOW(), NOW()),
        (v_client_id, 'BOG 39891 LA RIVIERA', false, NOW(), NOW()),
        (v_client_id, 'BOG 38997 MINUTO 80', false, NOW(), NOW()),
        (v_client_id, 'BOG 39435 UNIMINUTO', false, NOW(), NOW()),
        (v_client_id, 'BOG 39231 FLORIDA 89', false, NOW(), NOW()),
        (v_client_id, 'BOG 38949 EDS HERGOS', false, NOW(), NOW()),
        (v_client_id, 'BOG 34573 DIVER PLAZA', false, NOW(), NOW()),
        (v_client_id, 'BOG 38741 AZAFRANES', false, NOW(), NOW()),
        (v_client_id, 'BOG 39069 ARRAYANES', false, NOW(), NOW()),
        (v_client_id, 'BOG 38835 ALAMOS NORTE', false, NOW(), NOW()),
        (v_client_id, 'BOG 39763 PARIS GA ITAN', false, NOW(), NOW()),
        (v_client_id, 'BOG 39439 SANTA MARIA 73', false, NOW(), NOW()),
        (v_client_id, 'BOG 27588 SANTA HELENITA', false, NOW(), NOW()),
        (v_client_id, 'BOG 36798 QUIRIGUA', false, NOW(), NOW()),
        (v_client_id, 'BOG 39741 SERENA', false, NOW(), NOW()),
        (v_client_id, 'BOG 38671 78 KENNEDY', false, NOW(), NOW()),
        (v_client_id, 'BOG 38651 73 KENNEDY', false, NOW(), NOW()),
        (v_client_id, 'BOG 39099 VENECIA KRA 54', false, NOW(), NOW()),
        (v_client_id, 'BOG 38797 TEJAR 3', false, NOW(), NOW()),
        (v_client_id, 'BOG 38913 SAN ESTEBAN', false, NOW(), NOW()),
        (v_client_id, 'BOG 38957 PROVIVIENDA ORIENTAL', false, NOW(), NOW()),
        (v_client_id, 'BOG 38707 MURANO', false, NOW(), NOW()),
        (v_client_id, 'BOG 39117 LOS FUNDADORES', false, NOW(), NOW()),
        (v_client_id, 'BOG 38577 HIPOTECHO SUR', false, NOW(), NOW()),
        (v_client_id, 'BOG 35269 AMERICA OCCIDENTAL', false, NOW(), NOW()),
        (v_client_id, 'BOG 39895 MARSELLA 70', false, NOW(), NOW()),
        (v_client_id, 'BOG 39835 AMERICAS', false, NOW(), NOW()),
        (v_client_id, 'BOG 39293 VILLA DEL RIO', false, NOW(), NOW()),
        (v_client_id, 'BOG 38911 TORRES DE TIMIZA', false, NOW(), NOW()),
        (v_client_id, 'BOG 38853 NUEVO KENNEDY', false, NOW(), NOW()),
        (v_client_id, 'BOG 38921 KENNEDY SUR', false, NOW(), NOW()),
        (v_client_id, 'BOG 35972 KENNEDY CENTRAL', false, NOW(), NOW()),
        (v_client_id, 'BOG 38965 EDS CARVAJAL', false, NOW(), NOW()),
        (v_client_id, 'BOG 39331 CARRERA 80', false, NOW(), NOW()),
        (v_client_id, 'BOG 39283 AV QUIMBAYA', false, NOW(), NOW()),
        (v_client_id, 'BOG 39759 OLARTE', false, NOW(), NOW()),
        (v_client_id, 'BOG 39587 EDS TIMIZA', false, NOW(), NOW()),
        (v_client_id, 'BOG 39883 KENNEDY 36', false, NOW(), NOW()),
        (v_client_id, 'SOA 39055 SOACHA BOCHICA', false, NOW(), NOW()),
        (v_client_id, 'SOA 39541 SAN MATEO', false, NOW(), NOW()),
        (v_client_id, 'BOG 39063 EDS EL PIRE', false, NOW(), NOW()),
        (v_client_id, 'BOG 39219 CIUDAD ROMA', false, NOW(), NOW()),
        (v_client_id, 'BOG 38585 BRITALIA', false, NOW(), NOW()),
        (v_client_id, 'BOG 34532 BOSA ZONA BANCARIA', false, NOW(), NOW()),
        (v_client_id, 'BOG 38985 BOSA LOS NARANJOS', false, NOW(), NOW()),
        (v_client_id, 'BOG 39585 BOSA MARYLAND', false, NOW(), NOW()),
        (v_client_id, 'BOG 38845 VERSALLES', false, NOW(), NOW()),
        (v_client_id, 'BOG 38685 MAR', false, NOW(), NOW()),
        (v_client_id, 'BOG 38607 LA LAGUNA', false, NOW(), NOW()),
        (v_client_id, 'BOG 38739 FONTIBON CENTRAL', false, NOW(), NOW()),
        (v_client_id, 'BOG 39411 FONTIBON', false, NOW(), NOW()),
        (v_client_id, 'BOG 39077 EDS EL CARMEN', false, NOW(), NOW()),
        (v_client_id, 'BOG 39259 BOSTON', false, NOW(), NOW()),
        (v_client_id, 'BOG 38581 SAN GABRIEL', false, NOW(), NOW()),
        (v_client_id, 'BOG 39457 MERIDIANO 13 DEL EST', false, NOW(), NOW()),
        (v_client_id, 'BOG 38665 CASTILLA 78', false, NOW(), NOW()),
        (v_client_id, 'BOG 38705 BARRIO BAVARIA', false, NOW(), NOW()),
        (v_client_id, 'BOG 38649 ALSACIA', false, NOW(), NOW()),
        (v_client_id, 'BOG 38677 72 CASTILLA', false, NOW(), NOW()),
        (v_client_id, 'BOG 37381 ZONA IN', false, NOW(), NOW()),
        (v_client_id, 'BOG 39245 ROTONDA 60', false, NOW(), NOW()),
        (v_client_id, 'BOG 39581 GRANJAS', false, NOW(), NOW()),
        (v_client_id, 'BOG 39051 ESTACION CENTRAL', false, NOW(), NOW()),
        (v_client_id, 'BOG 39365 EL EJIDO', false, NOW(), NOW()),
        (v_client_id, 'BOG 39309 CENTRIK VIEW', false, NOW(), NOW()),
        (v_client_id, 'BOG 39983 LA FELICIDAD 75', false, NOW(), NOW()),
        (v_client_id, 'BOG 38757 VAR AV 68', false, NOW(), NOW()),
        (v_client_id, 'BOG 38825 SAN MIGUEL', false, NOW(), NOW()),
        (v_client_id, 'BOG 38785 LA MERCED NORTE', false, NOW(), NOW()),
        (v_client_id, 'BOG 39305 LA CORONA', false, NOW(), NOW()),
        (v_client_id, 'BOG 38631 CARRERA 24', false, NOW(), NOW()),
        (v_client_id, 'BOG 39511 FLAZA FID', false, NOW(), NOW()),
        (v_client_id, 'BOG 19012 PILOTO', false, NOW(), NOW()),
        (v_client_id, 'BOG 39041 HIPPIES CRA 7', false, NOW(), NOW()),
        (v_client_id, 'BOG 39451 FLORES 68', false, NOW(), NOW()),
        (v_client_id, 'BOG 14801 COSMOS', false, NOW(), NOW()),
        (v_client_id, 'BOG 16319 CHAPINERO', false, NOW(), NOW()),
        (v_client_id, 'BOG 38831 SALVADOR', false, NOW(), NOW()),
        (v_client_id, 'BOG 39047 QUESADA 52', false, NOW(), NOW()),
        (v_client_id, 'BOG 38653 GALERIAS 53', false, NOW(), NOW()),
        (v_client_id, 'BOG 39195 GALERIAS 28', false, NOW(), NOW()),
        (v_client_id, 'BOG 38709 FEDERMAN', false, NOW(), NOW()),
        (v_client_id, 'BOG 30139 ZONA 41', false, NOW(), NOW()),
        (v_client_id, 'BOG 35834 SAUZALITO', false, NOW(), NOW()),
        (v_client_id, 'BOG 38699 SALITRE', false, NOW(), NOW()),
        (v_client_id, 'BOG 39285 PASEO GRAN AMERICA', false, NOW(), NOW()),
        (v_client_id, 'BOG 38609 GRECO', false, NOW(), NOW()),
        (v_client_id, 'BOG 38743 CIUDAD UNIVERSITARIA', false, NOW(), NOW()),
        (v_client_id, 'BOG 39513 BURO 24', false, NOW(), NOW()),
        (v_client_id, 'BOG 38717 PARQUE MODELIA', false, NOW(), NOW()),
        (v_client_id, 'BOG 34834 CENTRAL POINT', false, NOW(), NOW()),
        (v_client_id, 'BOG 38783 CAPELLANIA', false, NOW(), NOW()),
        (v_client_id, 'BOG 39121 CANTABRIA', false, NOW(), NOW()),
        (v_client_id, 'BOG 38659 BALEARES', false, NOW(), NOW()),
        (v_client_id, 'BOG 40049 MERCED 71', false, NOW(), NOW()),
        (v_client_id, 'BOG 38657 PRADO 129', false, NOW(), NOW()),
        (v_client_id, 'BOG 38673 BACATA', false, NOW(), NOW()),
        (v_client_id, 'BOG 39397 VILLA RINCON', false, NOW(), NOW()),
        (v_client_id, 'BOG 38895 SUBA NAVETAS', false, NOW(), NOW()),
        (v_client_id, 'BOG 38601 SUBA 103', false, NOW(), NOW()),
        (v_client_id, 'BOG 39291 IMPERIAL', false, NOW(), NOW()),
        (v_client_id, 'BOG 39433 FIESTA SUBA', false, NOW(), NOW()),
        (v_client_id, 'BOG 38597 EL REINCON', false, NOW(), NOW()),
        (v_client_id, 'BOG 38595 COSTA AZUL', false, NOW(), NOW()),
        (v_client_id, 'BOG 39783 EDS SUBA SALITRE', false, NOW(), NOW()),
        (v_client_id, 'BOG 39423 TORRE SAPIENCIA', false, NOW(), NOW()),
        (v_client_id, 'BOG 38727 PRADO SUR', false, NOW(), NOW()),
        (v_client_id, 'BOG 38711 EDS IBERIA', false, NOW(), NOW()),
        (v_client_id, 'BOG 38623 SUBAZAR 92', false, NOW(), NOW()),
        (v_client_id, 'BOG 38753 RESERVA DE COLINA', false, NOW(), NOW()),
        (v_client_id, 'BOG 17917 PLAZA SUBA', false, NOW(), NOW()),
        (v_client_id, 'BOG 39007 LA CAMPIÑA', false, NOW(), NOW()),
        (v_client_id, 'BOG 38847 CIUDAD JARDIN', false, NOW(), NOW()),
        (v_client_id, 'BOG 14446 BRITANIA', false, NOW(), NOW()),
        (v_client_id, 'BOG 39811 CLUB POLICIA COLINA', false, NOW(), NOW()),
        (v_client_id, 'CHI 38813 SIMCA', false, NOW(), NOW()),
        (v_client_id, 'COT 39173 EL TREBOL', false, NOW(), NOW()),
        (v_client_id, 'COT 39103 EL LIBERTADOR', false, NOW(), NOW()),
        (v_client_id, 'COT 39027 EDS COTA', false, NOW(), NOW()),
        (v_client_id, 'CHI 38843 CIRCASIA', false, NOW(), NOW()),
        (v_client_id, 'CHI 38759 CENTRAL PARK', false, NOW(), NOW()),
        (v_client_id, 'CHI 38873 CAMPINCITO', false, NOW(), NOW()),
        (v_client_id, 'COT 38861 TERMINAL TERRESTRE', false, NOW(), NOW()),
        (v_client_id, 'COT 39105 EDS NUEVA GRANADA', false, NOW(), NOW()),
        (v_client_id, 'COT 38909 EDS NOVOTECH', false, NOW(), NOW()),
        (v_client_id, 'COT 39367 EDS EL DIAMANTE', false, NOW(), NOW()),
        (v_client_id, 'CHI 38951 TRES ESQUINAS', false, NOW(), NOW()),
        (v_client_id, 'CAJ 38893 TERRANOVA', false, NOW(), NOW()),
        (v_client_id, 'CAJ 38975 MILLA DE ORO', false, NOW(), NOW()),
        (v_client_id, 'CAJ 38823 MIDTOWN', false, NOW(), NOW()),
        (v_client_id, 'CHI 38919 CHIA FIQUE', false, NOW(), NOW()),
        (v_client_id, 'CAJ 38979 CAJICA FONTANA COMER', false, NOW(), NOW()),
        (v_client_id, 'CAJ 39071 CAJICA EL EDEN', false, NOW(), NOW()),
        (v_client_id, 'CHI 38655 BARCELONA', false, NOW(), NOW()),
        (v_client_id, 'CHI 38693 AV PARADILLA', false, NOW(), NOW()),
        (v_client_id, 'CHI 39075 ACQUA', false, NOW(), NOW()),
        (v_client_id, 'CAJ 38973 EDS WELLNWAA', false, NOW(), NOW()),
        (v_client_id, 'BOG 39539 PORVENIR 72', false, NOW(), NOW()),
        (v_client_id, 'BOG 38841 VILLA LUZ 77', false, NOW(), NOW()),
        (v_client_id, 'BOG 38621 SAN SEBASTIAN', false, NOW(), NOW()),
        (v_client_id, 'BOG 38703 ROJAS', false, NOW(), NOW()),
        (v_client_id, 'BOG 38733 ESTRADA', false, NOW(), NOW()),
        (v_client_id, 'BOG 39201 BOYACA 53', false, NOW(), NOW()),
        (v_client_id, 'BOG 38805 BONANZA', false, NOW(), NOW()),
        (v_client_id, 'BOG 39449 ACAPULCO', false, NOW(), NOW()),
        (v_client_id, 'BOG 39833 NORMANCIA 53', false, NOW(), NOW()),
        (v_client_id, 'BOG 39553 BOYACA PARQUE', false, NOW(), NOW()),
        (v_client_id, 'BOG 39101 RESTREPO OCCIDENTAL', false, NOW(), NOW()),
        (v_client_id, 'BOG 18621 LA CANDELARIA', false, NOW(), NOW()),
        (v_client_id, 'BOG 38691 GUATOQUE', false, NOW(), NOW()),
        (v_client_id, 'BOG 34604 CENTRO CRA 7', false, NOW(), NOW()),
        (v_client_id, 'BOG 20708 CATEDRAL', false, NOW(), NOW()),
        (v_client_id, 'BOG 38937 LA FRAGUITA', false, NOW(), NOW()),
        (v_client_id, 'BOG 39795 SEVILLA', false, NOW(), NOW()),
        (v_client_id, 'BOG 39275 TIBANA OPORTO', false, NOW(), NOW()),
        (v_client_id, 'BOG 38143 SANTA MATILDE', false, NOW(), NOW()),
        (v_client_id, 'BOG 38589 SAN BERNABE', false, NOW(), NOW()),
        (v_client_id, 'BOG 39193 JORGE GAITAN', false, NOW(), NOW()),
        (v_client_id, 'BOG 39191 JAZMIN', false, NOW(), NOW()),
        (v_client_id, 'BOG 39409 ISABEL 28', false, NOW(), NOW()),
        (v_client_id, 'BOG 39369 EDS VERAGUAS', false, NOW(), NOW()),
        (v_client_id, 'BOG 39723 LAFRAGUA', false, NOW(), NOW()),
        (v_client_id, 'BOG 36159 UAN SUR', false, NOW(), NOW()),
        (v_client_id, 'BOG 39223 SANTIAGO PEREZ', false, NOW(), NOW()),
        (v_client_id, 'BOG 39279 RESTREPO CARRERA 18', false, NOW(), NOW()),
        (v_client_id, 'BOG 19043 QUIROGA', false, NOW(), NOW()),
        (v_client_id, 'BOG 38599 PARQUE RESTREPO', false, NOW(), NOW()),
        (v_client_id, 'BOG 38947 LUNA PARK', false, NOW(), NOW()),
        (v_client_id, 'BOG 39515 COUNTRY SUR', false, NOW(), NOW()),
        (v_client_id, 'BOG 39867 CIUDADJARDIN', false, NOW(), NOW()),
        (v_client_id, 'BOG 39839 MONTES', false, NOW(), NOW()),
        (v_client_id, 'BOG 39261 LA URIBE', false, NOW(), NOW()),
        (v_client_id, 'BOG 15317 MODERNO', false, NOW(), NOW()),
        (v_client_id, 'BOG 38809 CALLE 77', false, NOW(), NOW()),
        (v_client_id, 'BOG 39437 SEPTIMA 49', false, NOW(), NOW()),
        (v_client_id, 'BOG 39841 CARACAS 64', false, NOW(), NOW()),
        (v_client_id, 'BOG 39093 TEUSAQUILLO 2725', false, NOW(), NOW()),
        (v_client_id, 'BOG 39523 NATIONAL PARK', false, NOW(), NOW()),
        (v_client_id, 'BOG 17309 JAVERIANA', false, NOW(), NOW()),
        (v_client_id, 'BOG 38795 CONCEJO', false, NOW(), NOW()),
        (v_client_id, 'BOG 38715 CALLE 34', false, NOW(), NOW()),
        (v_client_id, 'BOG 30719 UNIVERSITARIO', false, NOW(), NOW()),
        (v_client_id, 'BOG 36876 SEPTIMA NIEVES', false, NOW(), NOW()),
        (v_client_id, 'BOG 39005 LIMA 19', false, NOW(), NOW()),
        (v_client_id, 'BOG 27678 EJE AMBIENTAL', false, NOW(), NOW()),
        (v_client_id, 'BOG 18620 CALLE 19', false, NOW(), NOW()),
        (v_client_id, 'BOG 38969 ALAMEDA 13', false, NOW(), NOW()),
        (v_client_id, 'BOG 39725 7-24', false, NOW(), NOW()),
        (v_client_id, 'BOG 39875 TADEO', false, NOW(), NOW()),
        (v_client_id, 'BOG 16723 TOBERIN CENTRO', false, NOW(), NOW()),
        (v_client_id, 'BOG 39257 JARDINES DEL ORIENTE', false, NOW(), NOW()),
        (v_client_id, 'BOG 38719 BAVIERA 174', false, NOW(), NOW()),
        (v_client_id, 'BOG 39703 BRITALIA NORTE', false, NOW(), NOW()),
        (v_client_id, 'BOG 39159 ALCALA', false, NOW(), NOW()),
        (v_client_id, 'BOG 39863 URBAN 165', false, NOW(), NOW()),
        (v_client_id, 'BOG 39307 ANTIGUA', false, NOW(), NOW()),
        (v_client_id, 'BOG 16403 140', false, NOW(), NOW()),
        (v_client_id, 'BOG 39739 CAMPO ALTO', false, NOW(), NOW()),
        (v_client_id, 'BOG 39707 GRANADA HILLS', false, NOW(), NOW()),
        (v_client_id, 'BOG 39865 SANTA BAR CRA7', false, NOW(), NOW()),
        (v_client_id, 'BOG 15319 SHAIO', false, NOW(), NOW()),
        (v_client_id, 'BOG 39447 TERRAZE 183', false, NOW(), NOW()),
        (v_client_id, 'BOG 36796 TORRE 100', false, NOW(), NOW()),
        (v_client_id, 'BOG 30022 MORATO', false, NOW(), NOW()),
        (v_client_id, 'BOG 39281 CHICO 97', false, NOW(), NOW()),
        (v_client_id, 'BOG 38875 CHICO 100 CON 11', false, NOW(), NOW()),
        (v_client_id, 'BOG 38593 CASTELLANA', false, NOW(), NOW()),
        (v_client_id, 'BOG 39009 CAPITAL TOWERS', false, NOW(), NOW()),
        (v_client_id, 'BOG 38777 AUTONORTE 100', false, NOW(), NOW()),
        (v_client_id, 'BOG 29929 AUTO 100', false, NOW(), NOW()),
        (v_client_id, 'BOG 35480 VILLAMARIA', false, NOW(), NOW()),
        (v_client_id, 'BOG 38613 VILLA PRADO', false, NOW(), NOW()),
        (v_client_id, 'BOG 38641 SUBA 151', false, NOW(), NOW()),
        (v_client_id, 'BOG 19286 SANTA MARGARITA', false, NOW(), NOW()),
        (v_client_id, 'BOG 38897 SANTA BIBIANA 106', false, NOW(), NOW()),
        (v_client_id, 'BOG 38141 SANTA BAR', false, NOW(), NOW()),
        (v_client_id, 'BOG 38755 SAN PATRICIO 106', false, NOW(), NOW()),
        (v_client_id, 'BOG 38587 PUENTE 116', false, NOW(), NOW()),
        (v_client_id, 'BOG 38625 PARQUE VILLAS', false, NOW(), NOW()),
        (v_client_id, 'BOG 36953 NORTH POINT', false, NOW(), NOW()),
        (v_client_id, 'BOG 38799 NAVARRA 114', false, NOW(), NOW()),
        (v_client_id, 'BOG 36437 MULTCENTRO', false, NOW(), NOW()),
        (v_client_id, 'BOG 38917 MOLINOS DEL NORTE', false, NOW(), NOW()),
        (v_client_id, 'BOG 38667 GRADECO', false, NOW(), NOW()),
        (v_client_id, 'BOG 38807 ESTRELLA NORTE', false, NOW(), NOW()),
        (v_client_id, 'BOG 34474 ESTACION PEPE SIERRA', false, NOW(), NOW()),
        (v_client_id, 'BOG 35619 EL BOSQUE', false, NOW(), NOW()),
        (v_client_id, 'BOG 16726 CEDRO', false, NOW(), NOW()),
        (v_client_id, 'BOG 16727 CEDRITOS', false, NOW(), NOW()),
        (v_client_id, 'BOG 38637 CAMINO DEL NORTE', false, NOW(), NOW()),
        (v_client_id, 'BOG 38713 CALLE 166', false, NOW(), NOW()),
        (v_client_id, 'BOG 38627 CALLE 138', false, NOW(), NOW()),
        (v_client_id, 'BOG 38571 CALLE 116', false, NOW(), NOW()),
        (v_client_id, 'BOG 17992 CALATRAVA', false, NOW(), NOW()),
        (v_client_id, 'BOG 35719 BATAN', false, NOW(), NOW()),
        (v_client_id, 'BOG 15318 AUTOPISTA', false, NOW(), NOW()),
        (v_client_id, 'BOG 34473 ATABANZA', false, NOW(), NOW()),
        (v_client_id, 'BOG 38687 ACOMEDICA', false, NOW(), NOW()),
        (v_client_id, 'BOG 39619 RESERVA DEL CEDRO', false, NOW(), NOW()),
        (v_client_id, 'BOG 39547 EMPRE SANTA BAR', false, NOW(), NOW()),
        (v_client_id, 'BOG 40045 TORRE 108', false, NOW(), NOW()),
        (v_client_id, 'BOG 38735 TRANSMIHEROES', false, NOW(), NOW()),
        (v_client_id, 'BOG 38849 VISCAYA', false, NOW(), NOW()),
        (v_client_id, 'BOG 36797 TRADE CENTER', false, NOW(), NOW()),
        (v_client_id, 'BOG 39269 RINCON DE LOS ANDES', false, NOW(), NOW()),
        (v_client_id, 'BOG 38619 POLO', false, NOW(), NOW()),
        (v_client_id, 'BOG 38723 NOGALES 76', false, NOW(), NOW()),
        (v_client_id, 'BOG 38833 LOS MONJES', false, NOW(), NOW()),
        (v_client_id, 'BOG 38789 FIJAR 93', false, NOW(), NOW()),
        (v_client_id, 'BOG 29848 EL RETIRO', false, NOW(), NOW()),
        (v_client_id, 'BOG 26442 CHICO', false, NOW(), NOW()),
        (v_client_id, 'BOG 29258 CALLE 95', false, NOW(), NOW()),
        (v_client_id, 'BOG 24349 CALLE 93', false, NOW(), NOW()),
        (v_client_id, 'BOG 39023 ALAMOS INDUSTRIAL', false, NOW(), NOW()),
        (v_client_id, 'BOG 38879 UNILAGO', false, NOW(), NOW()),
        (v_client_id, 'BOG 35623 TORRE VIVA 26', false, NOW(), NOW()),
        (v_client_id, 'BOG 34614 SANTO TOMAS', false, NOW(), NOW()),
        (v_client_id, 'BOG 38701 SAN LUIS', false, NOW(), NOW()),
        (v_client_id, 'BOG 38697 PORTAL JAVERIANA', false, NOW(), NOW()),
        (v_client_id, 'BOG 38731 PARQUE ALCAZARES', false, NOW(), NOW()),
        (v_client_id, 'BOG 16321 PALMAS', false, NOW(), NOW()),
        (v_client_id, 'BOG 17638 PALERMO', false, NOW(), NOW()),
        (v_client_id, 'BOG 27592 LAGO GAITAN', false, NOW(), NOW()),
        (v_client_id, 'BOG 38675 LA 82', false, NOW(), NOW()),
        (v_client_id, 'BOG 18835 JJ VAR', false, NOW(), NOW()),
        (v_client_id, 'BOG 38821 INFINITUM', false, NOW(), NOW()),
        (v_client_id, 'BOG 16724 HEROES', false, NOW(), NOW()),
        (v_client_id, 'BOG 38139 ELEMENTO', false, NOW(), NOW()),
        (v_client_id, 'BOG 29928 EL DORADO', false, NOW(), NOW()),
        (v_client_id, 'BOG 37355 DORADO PLAZA', false, NOW(), NOW()),
        (v_client_id, 'BOG 38859 CARRERA 9 QC', false, NOW(), NOW()),
        (v_client_id, 'BOG 36952 CAPITAL CENTER', false, NOW(), NOW()),
        (v_client_id, 'BOG 18485 CALLE 67', false, NOW(), NOW()),
        (v_client_id, 'BOG 38567 CALLE 59', false, NOW(), NOW()),
        (v_client_id, 'BOG 39021 CALLE 48', false, NOW(), NOW()),
        (v_client_id, 'BOG 38661 CALLE 45', false, NOW(), NOW()),
        (v_client_id, 'BOG 38573 CALLE 44', false, NOW(), NOW()),
        (v_client_id, 'BOG 39311 AUTOPISTA 97', false, NOW(), NOW()),
        (v_client_id, 'BOG 39873 VIRREY 90', false, NOW(), NOW()),
        (v_client_id, 'BOG 39989 BARRIOS UNIDOS', false, NOW(), NOW()),
        (v_client_id, 'BOG 39971 CALLE 85', false, NOW(), NOW()),
        (v_client_id, 'BOG 40021 VILLAS 95', false, NOW(), NOW()),
        (v_client_id, 'BOG 39843 MODELO NORTE', false, NOW(), NOW()),
        (v_client_id, 'BOG 39967 FLORESTA 68 NORTE', false, NOW(), NOW()),
        (v_client_id, 'BOG 39059 ADTIVO ZONA FRANCA', false, NOW(), NOW()),
        (v_client_id, 'BOG 26275 CONECTA', false, NOW(), NOW()),
        (v_client_id, 'BOG 34475 SAN VICTORINO', false, NOW(), NOW()),
        (v_client_id, 'BOG 39017 PRIMERA 27', false, NOW(), NOW()),
        (v_client_id, 'BOG 38615 PLAZA RESTREPO', false, NOW(), NOW()),
        (v_client_id, 'BOG 39053 EL PROGRESO', false, NOW(), NOW()),
        (v_client_id, 'BOG 27281 BONAVISTA', false, NOW(), NOW()),
        (v_client_id, 'BOG 35481 1ERO DE MAYO', false, NOW(), NOW()),
        (v_client_id, 'BOG 34736 ZONA FRANCIA', false, NOW(), NOW()),
        (v_client_id, 'BOG 35969 TORRE AMERICAS', false, NOW(), NOW()),
        (v_client_id, 'BOG 38489 SOLUZONA', false, NOW(), NOW()),
        (v_client_id, 'BOG 35973 SAN ANDRESITO', false, NOW(), NOW()),
        (v_client_id, 'BOG 38995 SALAZAR GOMEZ', false, NOW(), NOW()),
        (v_client_id, 'BOG 38603 QUINTA PAREDES', false, NOW(), NOW()),
        (v_client_id, 'BOG 18424 PROCURADURIA', false, NOW(), NOW()),
        (v_client_id, 'BOG 39263 PASEO SEVILLA', false, NOW(), NOW()),
        (v_client_id, 'BOG 16725 PALOQUEMAO', false, NOW(), NOW()),
        (v_client_id, 'BOG 30137 MONTEVIDEO', false, NOW(), NOW()),
        (v_client_id, 'BOG 17918 MAGDALENA', false, NOW(), NOW()),
        (v_client_id, 'BOG 39127 LUSITANIA AV 68', false, NOW(), NOW()),
        (v_client_id, 'BOG 38681 LA ESTRELLA 1', false, NOW(), NOW()),
        (v_client_id, 'BOG 38583 KENNEDY CLL 26', false, NOW(), NOW()),
        (v_client_id, 'BOG 38959 ESTACION RICAUTE', false, NOW(), NOW()),
        (v_client_id, 'BOG 38963 EDS ZONA INDUSTRIAL', false, NOW(), NOW()),
        (v_client_id, 'BOG 39025 EDS LAS AGUAS', false, NOW(), NOW()),
        (v_client_id, 'BOG 18933 DECIMA SAN DIEGO', false, NOW(), NOW()),
        (v_client_id, 'BOG 36655 CUAN', false, NOW(), NOW()),
        (v_client_id, 'BOG 36158 CALIMA', false, NOW(), NOW()),
        (v_client_id, 'BOG 38961 BOSQUE IZQUIERDO', false, NOW(), NOW()),
        (v_client_id, 'BOG 39653 TRINIDAD GALAN', false, NOW(), NOW()),
        (v_client_id, 'BOG 38647 SAN JOSE', false, NOW(), NOW()),
        (v_client_id, 'BOG 38663 MODELA', false, NOW(), NOW()),
        (v_client_id, 'BOG 39945 MUSEO DEL ORO', false, NOW(), NOW())
    ON CONFLICT DO NOTHING;

    RAISE NOTICE 'Se han insertado todas las sucursales para el cliente Oxxo';

END $$;

-- Verificar el resultado
SELECT
    c.name as cliente,
    COUNT(b.id) as total_sucursales,
    COUNT(CASE WHEN b.is_main THEN 1 END) as sucursales_principales
FROM clients c
LEFT JOIN branches b ON b.client_id = c.id
WHERE c.name = 'Oxxo'
GROUP BY c.id, c.name;
