-- Agregar columna de categoria a la tabla de productos
ALTER TABLE products 
ADD COLUMN category VARCHAR(10) DEFAULT 'PT' CHECK (category IN ('PT', 'MP'));

-- Crear índice para mejorar consultas por categoría
CREATE INDEX IF NOT EXISTS idx_products_category ON products(category);

-- Insertar todas las materias primas (MP)
INSERT INTO products (name, category, unit, description) VALUES
('ACEITE DE OLIVA', 'MP', 'lt', 'Aceite de oliva para cocina'),
('ACEITE VEGETAL', 'MP', 'lt', 'Aceite vegetal para fritura'),
('ACIDO CITRICO', 'MP', 'kg', 'Ácido cítrico conservante'),
('ADDIGERM CHOCOL 5%SA', 'MP', 'kg', 'Aditivo para chocolate'),
('ADDIGERM SOFTNESS', 'MP', 'kg', 'Aditivo suavizante'),
('AGUA POTABLE TRATADA', 'MP', 'lt', 'Agua tratada para producción'),
('AHUYAMA', 'MP', 'kg', 'Calabaza fresca'),
('AJO', 'MP', 'kg', 'Ajo fresco'),
('Ajo en Polvo', 'MP', 'kg', 'Ajo deshidratado en polvo'),
('ALBAHACA', 'MP', 'kg', 'Albahaca fresca'),
('ALBAHACA DESHIDRATADA', 'MP', 'kg', 'Albahaca seca'),
('ALMENDRA TAJADA', 'MP', 'kg', 'Almendras laminadas'),
('ALMIDON DE MAIZ', 'MP', 'kg', 'Almidón de maíz'),
('ALMIDON DE YUCA', 'MP', 'kg', 'Almidón de yuca'),
('ALMIDON MODIFICADO', 'MP', 'kg', 'Almidón modificado'),
('APIO', 'MP', 'kg', 'Apio fresco'),
('ARANDANO DESHIDRATADOS', 'MP', 'kg', 'Arándanos secos'),
('AREQUIPE MANJAR BLANCO', 'MP', 'kg', 'Dulce de leche'),
('AVENA EN HOJUELAS', 'MP', 'kg', 'Avena en hojuelas'),
('AZUCAR BLANCO GENERICO', 'MP', 'kg', 'Azúcar blanco refinado'),
('AZUCAR MORENA', 'MP', 'kg', 'Azúcar moreno'),
('BICARBONATO EN POLVO', 'MP', 'kg', 'Bicarbonato de sodio'),
('BOCADILLO SOLIDO', 'MP', 'kg', 'Bocadillo de guayaba'),
('BOLSATINA 30 X 30', 'MP', 'und', 'Bolsas plásticas 30x30'),
('BOLSATINA 50x100', 'MP', 'und', 'Bolsas plásticas 50x100'),
('BOLSATINA AZUL', 'MP', 'und', 'Bolsas plásticas azules'),
('BOLSATINA GRANDES 80*100', 'MP', 'und', 'Bolsas grandes 80x100'),
('BOLSATINA PEQUEÑA 60*60', 'MP', 'und', 'Bolsas pequeñas 60x60'),
('BOLSATINA ROJA 100*70', 'MP', 'und', 'Bolsas rojas 100x70'),
('BOLSATINA VERDE 100*70', 'MP', 'und', 'Bolsas verdes 100x70'),
('CAJA GRANDE C790 59X 39X 17', 'MP', 'und', 'Cajas de cartón grandes'),
('CAJA PEQUEÑA 39 X 26 X 17 CON RECUBRIMIENTO', 'MP', 'und', 'Cajas pequeñas con recubrimiento'),
('CAJA REGULAR CON LOGO', 'MP', 'und', 'Cajas regulares con logo'),
('CAJAS PIZZA JUAN VALDEZ 400*300*45', 'MP', 'und', 'Cajas para pizza Juan Valdez'),
('CANASTILLA ABATIBLE VERDE IFCO', 'MP', 'und', 'Canastillas verdes IFCO'),
('CANELA EN POLVO', 'MP', 'kg', 'Canela molida'),
('CARNE DESCARGUE', 'MP', 'kg', 'Carne de res'),
('CARNE MOLIDA', 'MP', 'kg', 'Carne molida'),
('Cebolla Blanca', 'MP', 'kg', 'Cebolla blanca fresca'),
('CEBOLLA EN POLVO', 'MP', 'kg', 'Cebolla deshidratada'),
('CEBOLLA ROJA', 'MP', 'kg', 'Cebolla roja fresca'),
('CEBOLLIN', 'MP', 'kg', 'Cebollín fresco'),
('CERNIDO DE GUAYABA', 'MP', 'kg', 'Pulpa de guayaba'),
('CHORIZO', 'MP', 'kg', 'Chorizo'),
('CHUNKS DE CHOCOLATE SEMIAMARGO', 'MP', 'kg', 'Trozos de chocolate'),
('CINTA', 'MP', 'mt', 'Cinta adhesiva'),
('CINTA FLOWPACK', 'MP', 'mt', 'Cinta para empaque'),
('CINTA TINTA IMPRESORA', 'MP', 'und', 'Cinta de impresora'),
('COCO RALLADO', 'MP', 'kg', 'Coco rallado'),
('COLOR AMARILLO', 'MP', 'kg', 'Colorante amarillo'),
('COLOR CARAMELO', 'MP', 'kg', 'Colorante caramelo'),
('COLOR VERDE', 'MP', 'kg', 'Colorante verde'),
('COLOR VERDE OLIVA', 'MP', 'kg', 'Colorante verde oliva'),
('COLORANTE ROJO', 'MP', 'kg', 'Colorante rojo'),
('COMINO', 'MP', 'kg', 'Comino en polvo'),
('CREMA DE LECHE', 'MP', 'lt', 'Crema de leche'),
('CREMA PASTELERA LEVAPAN', 'MP', 'kg', 'Crema pastelera Levapan'),
('CREMA PASTELERA POLVO', 'MP', 'kg', 'Crema pastelera en polvo'),
('CUAJADA', 'MP', 'kg', 'Cuajada fresca'),
('DIMODAN', 'MP', 'kg', 'Emulsificante Dimodan'),
('ENCINTADOR', 'MP', 'und', 'Máquina encintadora'),
('ESENCIA ALMENDRA', 'MP', 'lt', 'Esencia de almendra'),
('ESENCIA DE BANANO', 'MP', 'lt', 'Esencia de banano'),
('ESENCIA DE CANELA', 'MP', 'lt', 'Esencia de canela'),
('ESENCIA DE COCO', 'MP', 'lt', 'Esencia de coco'),
('ESENCIA DE MANTEQUILLA', 'MP', 'lt', 'Esencia de mantequilla'),
('ESENCIA DE VAINILLA BLANCA', 'MP', 'lt', 'Esencia de vainilla blanca'),
('ESENCIA DE VAINILLA CARAMELO', 'MP', 'lt', 'Esencia de vainilla caramelo'),
('Espinaca', 'MP', 'kg', 'Espinaca fresca'),
('ESQUINERO', 'MP', 'und', 'Esquineros de cartón'),
('ESTIBAS', 'MP', 'und', 'Estibas de madera'),
('ETIQUETA 50*50', 'MP', 'und', 'Etiquetas 50x50'),
('ETIQUETA PP 50*25', 'MP', 'und', 'Etiquetas PP 50x25'),
('ETIQUETA PP100*50 GRANDE', 'MP', 'und', 'Etiquetas grandes PP'),
('FECULA', 'MP', 'kg', 'Fécula'),
('GLUTEN MANITO-FR SCO', 'MP', 'kg', 'Gluten Manito'),
('GOMA GUAR', 'MP', 'kg', 'Goma guar'),
('GRANILLO CHOCOLATE SEMIAMARGO', 'MP', 'kg', 'Granillo de chocolate'),
('GRANOLIFE FRESH MEJORADOR', 'MP', 'kg', 'Mejorador Granolife'),
('HARINA ALMENDRA SIN PIEL', 'MP', 'kg', 'Harina de almendra'),
('HARINA DE MAIZ AMARILLA', 'MP', 'kg', 'Harina de maíz amarilla'),
('HARINA DE TRIGO MULTIPROPOSITO', 'MP', 'kg', 'Harina de trigo'),
('HARINA GALLETARINA', 'MP', 'kg', 'Harina para galletas'),
('HARINA INTEGRAL', 'MP', 'kg', 'Harina integral'),
('HARINA SM', 'MP', 'kg', 'Harina SM'),
('HIERBABUENA', 'MP', 'kg', 'Hierbabuena fresca'),
('HUEVO LIQUIDO PASTEURIZADO', 'MP', 'lt', 'Huevo líquido'),
('HUEVOS', 'MP', 'und', 'Huevos frescos'),
('JAMON', 'MP', 'kg', 'Jamón'),
('JAMON VILLASECA', 'MP', 'kg', 'Jamón Villaseca'),
('JENGIBRE EN POLVO', 'MP', 'kg', 'Jengibre molido'),
('JUGO DE LULO', 'MP', 'lt', 'Jugo de lulo'),
('LAMINA 26x39', 'MP', 'und', 'Láminas 26x39'),
('LAMINA 45x67', 'MP', 'und', 'Láminas 45x67'),
('LAMINA TRASPARENTE 30 X 30', 'MP', 'und', 'Láminas transparentes 30x30'),
('LAMINAS TRANSPARENTE EN POLIETILENO', 'MP', 'und', 'Láminas de polietileno'),
('LAUREL', 'MP', 'kg', 'Laurel fresco'),
('LAUREL HOJA', 'MP', 'kg', 'Hojas de laurel'),
('LECHE CONDENSADA', 'MP', 'kg', 'Leche condensada'),
('LECHE EN POLVO', 'MP', 'kg', 'Leche en polvo'),
('LECHE LIQUIDA ENTERA', 'MP', 'lt', 'Leche líquida entera'),
('LEVADURA', 'MP', 'kg', 'Levadura de panadería'),
('LEVADURA FRESCA', 'MP', 'kg', 'Levadura fresca'),
('LEVADURA SECA', 'MP', 'kg', 'Levadura seca'),
('LIMONARIA', 'MP', 'kg', 'Limonaria fresca'),
('LINAZA', 'MP', 'kg', 'Semillas de linaza'),
('MAIZ TIERNO', 'MP', 'kg', 'Maíz tierno'),
('MANGAS PASTELERAS', 'MP', 'und', 'Mangas pasteleras'),
('MANTEQUILLA PACOS', 'MP', 'kg', 'Mantequilla Pacos'),
('MANZANA GALA', 'MP', 'kg', 'Manzana Gala'),
('MANZANA VERDE EN CUBOS', 'MP', 'kg', 'Manzana verde en cubos'),
('MARGARINA CINCO ESTRELLAS', 'MP', 'kg', 'Margarina Cinco Estrellas'),
('MARGARINA DE EMPASTE', 'MP', 'kg', 'Margarina de empaste'),
('MARGARINA HOJALDRE', 'MP', 'kg', 'Margarina para hojaldre'),
('MEJORADOR BAKER BONUS', 'MP', 'kg', 'Mejorador Baker Bonus'),
('MEJORADOR MAGIMIX ROJO', 'MP', 'kg', 'Mejorador Magimix'),
('MEJORADOR PAN MINUTO', 'MP', 'kg', 'Mejorador Pan Minuto'),
('MIEL DE ABEJAS', 'MP', 'kg', 'Miel de abejas'),
('MIGA DE PAN', 'MP', 'kg', 'Miga de pan'),
('NATAMICINA', 'MP', 'kg', 'Natamicina conservante'),
('NC - FLAUTA DE CHOCOLATE 80 GR', 'MP', 'und', 'Flauta de chocolate 80gr'),
('OREGANO POLVO', 'MP', 'kg', 'Orégano en polvo'),
('PAPEL SILICONADO', 'MP', 'mt', 'Papel siliconado'),
('PAPRIKA', 'MP', 'kg', 'Paprika en polvo'),
('PASTA DE TOMATE', 'MP', 'kg', 'Pasta de tomate'),
('PASTEL DE POLLO CARBONARA 100g', 'MP', 'und', 'Pastel pollo carbonara'),
('PECHUGA DE POLLO', 'MP', 'kg', 'Pechuga de pollo'),
('PIMIENTA', 'MP', 'kg', 'Pimienta molida'),
('PIÑA', 'MP', 'kg', 'Piña fresca'),
('POLVO PARA HORNEAR', 'MP', 'kg', 'Polvo de hornear'),
('POLVO SALSA CARBONARA', 'MP', 'kg', 'Salsa carbonara en polvo'),
('PROPIONATO DE CALCIO', 'MP', 'kg', 'Propionato de calcio'),
('PROTEINA DE SOYA', 'MP', 'kg', 'Proteína de soya'),
('PROTEINA RESPONSE', 'MP', 'kg', 'Proteína Response'),
('QUESO CAMPESINO', 'MP', 'kg', 'Queso campesino'),
('QUESO COSTEÑO', 'MP', 'kg', 'Queso costeño'),
('QUESO COSTEÑO RALLADO', 'MP', 'kg', 'Queso costeño rallado'),
('QUESO CREMA', 'MP', 'kg', 'Queso crema'),
('QUESO DOBLE CREMA', 'MP', 'kg', 'Queso doble crema'),
('QUESO DOBLE CREMA TAJADO SEMIGRASO', 'MP', 'kg', 'Queso doble crema tajado'),
('QUESO MOZZARELA TAJADO', 'MP', 'kg', 'Queso mozzarella tajado'),
('QUESO PARMESANO', 'MP', 'kg', 'Queso parmesano'),
('QUESO PUFF 40 GRM', 'MP', 'und', 'Queso puff 40gr'),
('QUESO RICOTTA', 'MP', 'kg', 'Queso ricotta'),
('QUESO TIPO CHEDAR', 'MP', 'kg', 'Queso tipo cheddar'),
('QUINUA', 'MP', 'kg', 'Quinua'),
('RELLENO DE AVELLANAS', 'MP', 'kg', 'Relleno de avellanas'),
('RELLENO DE CARNE ARA 100g', 'MP', 'und', 'Relleno de carne 100g'),
('RELLENO PASTEL DE ESPINACA Y QUESO RICOTTA', 'MP', 'kg', 'Relleno espinaca ricotta'),
('ROLLO 48*27.5', 'MP', 'und', 'Rollos 48x27.5'),
('ROLLO 48*30 OXXO', 'MP', 'und', 'Rollos 48x30 Oxxo'),
('ROLLO 48*33', 'MP', 'und', 'Rollos 48x33'),
('ROLLO BOLSATINA ROJA', 'MP', 'mt', 'Rollo bolsatina roja'),
('ROLLO BOLSATINA TRASPARENTE', 'MP', 'mt', 'Rollo bolsatina transparente'),
('ROLLO BOLSATINA VERDE', 'MP', 'mt', 'Rollo bolsatina verde'),
('ROLLO CROISSANT EUROPA 60GR', 'MP', 'und', 'Rollo croissant 60gr'),
('ROLLO CROISSANT EUROPA 90GR', 'MP', 'und', 'Rollo croissant 90gr'),
('ROLLO CROISSANT MULTICEREAL', 'MP', 'und', 'Rollo croissant multicereal'),
('ROLLO PASTEL DE CARNE 120', 'MP', 'und', 'Rollo pastel carne 120gr'),
('ROLLO TINTA FLOWPACK', 'MP', 'und', 'Rollo tinta flowpack'),
('ROMERO', 'MP', 'kg', 'Romero fresco'),
('S-500 MASA LAMINADA', 'MP', 'kg', 'Masa laminada S-500'),
('SABOR ALMENDRAS', 'MP', 'lt', 'Sabor almendras'),
('SABOR MANZANA VERDE', 'MP', 'lt', 'Sabor manzana verde'),
('SABOR NARANJA', 'MP', 'lt', 'Sabor naranja'),
('Sabor nata', 'MP', 'lt', 'Sabor nata'),
('SABOR VAINILLA', 'MP', 'lt', 'Sabor vainilla'),
('SAL', 'MP', 'kg', 'Sal de cocina'),
('SALSA DEMI GLACE', 'MP', 'kg', 'Salsa demi glace'),
('SALVADO DE TRIGO', 'MP', 'kg', 'Salvado de trigo'),
('SEMILLA AMAPOLA', 'MP', 'kg', 'Semillas de amapola'),
('SEMILLAS AJONJOLI NEGRO', 'MP', 'kg', 'Ajonjolí negro'),
('SEMILLAS DE AJONJOLI BLANCO', 'MP', 'kg', 'Ajonjolí blanco'),
('SEMILLAS DE CHIA', 'MP', 'kg', 'Semillas de chía'),
('SUERO LACTEO', 'MP', 'lt', 'Suero lácteo'),
('SUNSET GLAZE', 'MP', 'kg', 'Glaseado Sunset'),
('TOCINETA AHUMADA', 'MP', 'kg', 'Tocineta ahumada'),
('TOMATE', 'MP', 'kg', 'Tomate fresco'),
('TOMILLO', 'MP', 'kg', 'Tomillo fresco'),
('TOMILLO HOJA', 'MP', 'kg', 'Hojas de tomillo'),
('VINAGRE', 'MP', 'lt', 'Vinagre blanco'),
('VINAGRE DE FRUTAS', 'MP', 'lt', 'Vinagre de frutas'),
('VINIPEL', 'MP', 'mt', 'Vinipel transparente'),
('VINIPEL AZUL', 'MP', 'mt', 'Vinipel azul'),
('VINO TINTO', 'MP', 'lt', 'Vino tinto'),
('ZANAHORIA', 'MP', 'kg', 'Zanahoria fresca');

-- Los productos se insertarán como nuevos registros

-- Actualizar productos existentes que no tengan categoría definida
UPDATE products 
SET category = 'PT' 
WHERE category IS NULL;

-- Comentarios sobre las categorías
-- PT = Producto Terminado (productos finales listos para venta)
-- MP = Materia Prima (ingredientes y materiales para producción)

-- Verificar el resultado
SELECT 
    category,
    COUNT(*) as total_productos
FROM products 
GROUP BY category
ORDER BY category;